FROM php:apache
RUN apt-get update && \
    apt-get install -y libpq-dev libpng-dev libjpeg-dev libfreetype6-dev && \
    docker-php-ext-configure gd --with-jpeg --with-freetype && \
    docker-php-ext-install pdo pdo_pgsql pgsql gd
COPY ./www/ /var/www/html/
COPY ./config/php/ /usr/local/etc/php/
COPY ./config/apache/apache2.conf /etc/apache2/apache2.conf
EXPOSE 80