FROM php:apache
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql
COPY ./www /var/www/html/
COPY ./php_config /usr/local/etc/php/
COPY ./apache_config/apache2.conf /etc/apache2/apache2.conf
EXPOSE 80
