version: "3"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache.prod
    ports:
      - 80:80

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres.prod
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=~a5Xf;UB}^3kchY
      - POSTGRES_DB=ecommerce
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    ports:
      - 8080:8080
