version: "3"
services:
  apache-prod:
    build:
      context: .
      dockerfile: Dockerfile-apache.prod
    ports:
      - 80:80

  postgres-prod:
    build:
      context: .
      dockerfile: Dockerfile-postgres.prod
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=~a5Xf;UB}^3kchY
      - POSTGRES_DB=ecommerce

  adminer:
    image: adminer
    ports:
      - 8080:8080
