version: "3"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache.dev
    ports:
      - 80:80
    volumes:
      - ./www/:/var/www/html/
      - ./config/php/:/usr/local/etc/php/
      - ./config/apache/apache2.conf:/etc/apache2/apache2.conf

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=~a5Xf;UB}^3kchY
      - POSTGRES_DB=ecommerce
    volumes:
      - ./config/postgres/:/docker-entrypoint-initdb.d/
      - ./postgres_data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    ports:
      - 8080:8080
