version: "3"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=~a5Xf;UB}^3kchY
      - POSTGRES_DB=ecommerce
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
